export * from './role.model';
export * from './department.model';
export * from './stream.model';
export * from './group.model';
export * from './user.model';
export * from './subject.model';
export * from './grade.model';
export * from './schedule-entry.model';
export * from './pending-request.model';
